version: '3.8'

services:
  front-end:
    build: 
      context: ./front-end
    container_name: portfolio-front-end
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge